name: TestBuild

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: yarn install --frozen-lockfile

      - name: Build
        run: NODE_ENV=production yarn build
